### ISSUE TITLE
E5 Carrito de Compras

### ISSUE THREAD

**Issue by Barcillo** [Barcillo/KFMC#1]
- [ ] Agregar producto al carrito
- [ ] Modificar productos en el carrito
- [ ] Eliminar producto del Carrito
- [ ] Procesar Venta
